---
title:
format:
  html:
    embed-resources: true
---

# Distances Between Observations

Read this notebook from top to bottom and fill in the code as you go. Work together and discuss with other students in the class. Try to resolve any errors on your own first, but don't get stuck; ask for help!

In addition to writing and running code, be sure to examine any output and interpret the results before moving on.

For many of these questions, there are several approaches, and there is no single right answer. You should try a few different things and compare with your classmates.

We will use `scikit-learn` extensively later, but for this activity you might want to stick with `pandas`.

In [1]:
import pandas as pd
import numpy as np

## Ames - Recommending Similar Homes

1\. Suppose that you really like house 0 in the Ames housing data set, but it is too expensive. Find cheaper homes that are similar to it --- in terms of living area, number of bedrooms, number of bathrooms --- by calculating distances from house 0. You might want to try different distance metrics and different scaling methods; how sensitive are your results to these choices?

Be sure to actually look at the profiles of the homes that your algorithm picked out as most similar (based on these 3 variables). Do they make sense?

_Think:_ If the goal is to find a "good deal" on a similar house, should sale price be included as a variable in your distance metric?

In [2]:
df_ames = pd.read_csv("https://dlsun.github.io/pods/data/AmesHousing.txt", sep="\t")
df_ames.shape

(2930, 82)

In [3]:
df_ames["Bathrooms"] = df_ames["Full Bath"] + 0.5 * df_ames["Half Bath"]

house0 = df_ames.loc[0]
show_vars = ["Gr Liv Area", "Bedroom AbvGr", "Bathrooms", "House Style", "Neighborhood", "Year Built", "SalePrice"]

house0[show_vars]

Gr Liv Area        1656
Bedroom AbvGr         3
Bathrooms           1.0
House Style      1Story
Neighborhood      NAmes
Year Built         1960
SalePrice        215000
Name: 0, dtype: object

In [4]:
X = df_ames[["Gr Liv Area", "Bedroom AbvGr", "Bathrooms"]].astype(float)
X_z = (X - X.mean()) / X.std()
diff = X_z - X_z.loc[0]
df_ames["euclid"] = np.sqrt((diff**2).sum(axis=1))
df_ames["manhattan"] = diff.abs().sum(axis=1)

In [5]:
df_cheaper = df_ames[df_ames["SalePrice"] < house0["SalePrice"]]
df_cheaper.sort_values("euclid")[show_vars + ["euclid"]].head()

,Gr Liv Area,Bedroom AbvGr,Bathrooms,House Style,Neighborhood,Year Built,SalePrice,euclid
1226,1661,3,1.0,SLvl,NAmes,1955,165500,0.009891
1940,1647,3,1.0,1Story,NAmes,1953,153000,0.017804
291,1666,3,1.0,1.5Fin,SWISU,1931,100000,0.019782
758,1666,3,1.0,1.5Fin,IDOTRR,1927,135000,0.019782
1357,1666,3,1.0,2Story,OldTown,1925,161000,0.019782

In [6]:
df_cheaper.sort_values("manhattan")[show_vars + ["manhattan"]].head()

,Gr Liv Area,Bedroom AbvGr,Bathrooms,House Style,Neighborhood,Year Built,SalePrice,manhattan
1226,1661,3,1.0,SLvl,NAmes,1955,165500,0.009891
1940,1647,3,1.0,1Story,NAmes,1953,153000,0.017804
1357,1666,3,1.0,2Story,OldTown,1925,161000,0.019782
758,1666,3,1.0,1.5Fin,IDOTRR,1927,135000,0.019782
291,1666,3,1.0,1.5Fin,SWISU,1931,100000,0.019782

In [7]:
X.loc[[0, 1226]]

      Gr Liv Area  Bedroom AbvGr  Bathrooms
0          1656.0            3.0        1.0
1226       1661.0            3.0        1.0

**The house that the model selected that is most close to house 0 has 2 of the 3 variables exactly the same, with only the Gr Liv Area variable being different (by only 5).**

2\. Continuing part 1. Suppose that you really like house 0 in the data set, but it is too expensive. Find cheaper homes that are similar to it --- in terms of living area, number of bedrooms, number of bathrooms, **and House Style** --- by calculating distances from house 0. You might want to try different distance metrics and different scaling methods; how sensitive are your results to these choices?

Be sure to actually look at the profiles of the homes that your algorithm picked out as most similar. Do they make sense?

In [8]:
# YOUR CODE HERE. ADD CELLS AS NEEDED
X = df_ames[["Gr Liv Area", "Bedroom AbvGr", "Bathrooms", "House Style"]]
X = pd.get_dummies(X) * 1
X

,Gr Liv Area,Bedroom AbvGr,Bathrooms,House Style_1.5Fin,House Style_1.5Unf,House Style_1Story,House Style_2.5Fin,House Style_2.5Unf,House Style_2Story,House Style_SFoyer,House Style_SLvl
0,1656,3,1.0,0,0,1,0,0,0,0,0
1,896,2,1.0,0,0,1,0,0,0,0,0
2,1329,3,1.5,0,0,1,0,0,0,0,0
3,2110,3,2.5,0,0,1,0,0,0,0,0
4,1629,3,2.5,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
2925,1003,3,1.0,0,0,0,0,0,0,0,1
2926,902,2,1.0,0,0,1,0,0,0,0,0
2927,970,3,1.0,0,0,0,0,0,0,1,0
2928,1389,2,1.0,0,0,1,0,0,0,0,0
2929,2000,3,2.5,0,0,0,0,0,1,0,0

In [9]:
X_z = (X - X.mean()) / X.std()
diff = X_z - X_z.loc[0]
df_ames["euclid"] = np.sqrt((diff**2).sum(axis=1))
df_ames["manhattan"] = diff.abs().sum(axis=1)
df_cheaper = df_ames[df_ames["SalePrice"] < house0["SalePrice"]]
df_cheaper.sort_values("euclid")[show_vars + ["euclid"]].head()

,Gr Liv Area,Bedroom AbvGr,Bathrooms,House Style,Neighborhood,Year Built,SalePrice,euclid
1940,1647,3,1.0,1Story,NAmes,1953,153000,0.017804
618,1644,3,1.0,1Story,NAmes,1953,167000,0.023738
2700,1640,3,1.0,1Story,Sawyer,1950,131000,0.031651
314,1687,3,1.0,1Story,Timber,1948,160000,0.061324
788,1689,3,1.0,1Story,Edwards,1956,127500,0.065281

In [10]:
df_cheaper.sort_values("manhattan")[show_vars + ["manhattan"]].head()

,Gr Liv Area,Bedroom AbvGr,Bathrooms,House Style,Neighborhood,Year Built,SalePrice,manhattan
1940,1647,3,1.0,1Story,NAmes,1953,153000,0.017804
618,1644,3,1.0,1Story,NAmes,1953,167000,0.023738
2700,1640,3,1.0,1Story,Sawyer,1950,131000,0.031651
314,1687,3,1.0,1Story,Timber,1948,160000,0.061324
788,1689,3,1.0,1Story,Edwards,1956,127500,0.065281

In [11]:
X.loc[[0, 1940]]

,Gr Liv Area,Bedroom AbvGr,Bathrooms,House Style_1.5Fin,House Style_1.5Unf,House Style_1Story,House Style_2.5Fin,House Style_2.5Unf,House Style_2Story,House Style_SFoyer,House Style_SLvl
0,1656,3,1.0,0,0,1,0,0,0,0,0
1940,1647,3,1.0,0,0,1,0,0,0,0,0

**Both the Euclidean and Manhattan distances picked house 1940 as the closest cheaper house to house 0. Looking at the variables, once again every variable is exactly the same except for `Gr Liv Area`, which in this case is only 9 off.**

3\. Continuing parts 1 and 2. Suppose that you really like house 0 in the data set, but it is too expensive. Find cheaper homes that are similar to it, by calculating distances. You can **choose the variables to include, but include both quantitative and categorical variables**. Be sure to actually look at the profiles of the homes that your algorithm picked out as most similar. Do they make sense?

You might want to try different distance metrics and different scaling methods; how sensitive are your results to these choices?

_Hint:_ There are many variables in the data set. Do not attempt to compute distance based on all the variables! You will want to pare down the number of variables, but be sure to include a mixture of categorical and quantitative variables. Refer to the [data documentation](https://ww2.amstat.org/publications/jse/v19n3/decock/DataDocumentation.txt) for information about the variables.

In [12]:
# YOUR CODE HERE. ADD CELLS AS NEEDED
X = df_ames[["Gr Liv Area", "Bedroom AbvGr", "Bathrooms", "House Style", "Lot Area", "Neighborhood", "Central Air"]]
X = pd.get_dummies(X) * 1
X

,Gr Liv Area,Bedroom AbvGr,Bathrooms,Lot Area,House Style_1.5Fin,House Style_1.5Unf,House Style_1Story,House Style_2.5Fin,House Style_2.5Unf,House Style_2Story,...,Neighborhood_OldTown,Neighborhood_SWISU,Neighborhood_Sawyer,Neighborhood_SawyerW,Neighborhood_Somerst,Neighborhood_StoneBr,Neighborhood_Timber,Neighborhood_Veenker,Central Air_N,Central Air_Y
0,1656,3,1.0,31770,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,896,2,1.0,11622,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,1329,3,1.5,14267,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,2110,3,2.5,11160,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,1629,3,2.5,13830,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,1003,3,1.0,7937,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2926,902,2,1.0,8885,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2927,970,3,1.0,10441,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2928,1389,2,1.0,10010,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2929,2000,3,2.5,9627,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1

In [13]:
X_z = (X - X.mean()) / X.std()
diff = X_z - X_z.loc[0]
df_ames["euclid"] = np.sqrt((diff**2).sum(axis=1))
df_ames["manhattan"] = diff.abs().sum(axis=1)
df_cheaper = df_ames[df_ames["SalePrice"] < house0["SalePrice"]]
df_cheaper.sort_values("euclid")[show_vars + ["euclid"]].head()

,Gr Liv Area,Bedroom AbvGr,Bathrooms,House Style,Neighborhood,Year Built,SalePrice,euclid
1895,1652,3,1.5,1Story,NAmes,1959,200000,1.463407
2590,2039,3,1.5,1Story,NAmes,1941,167000,1.716004
1896,1429,3,1.0,1Story,NAmes,1960,181900,2.226585
2359,1096,3,1.0,1Story,NAmes,1969,138800,2.301863
2618,1600,2,1.0,1Story,NAmes,1957,207500,2.305537

In [14]:
df_cheaper.sort_values("manhattan")[show_vars + ["manhattan"]].head()

,Gr Liv Area,Bedroom AbvGr,Bathrooms,House Style,Neighborhood,Year Built,SalePrice,manhattan
1895,1652,3,1.5,1Story,NAmes,1959,200000,2.025264
1240,1570,3,1.0,1Story,NAmes,1958,166800,2.526719
1896,1429,3,1.0,1Story,NAmes,1960,181900,2.629885
618,1644,3,1.0,1Story,NAmes,1953,167000,2.837184
1940,1647,3,1.0,1Story,NAmes,1953,153000,2.839879

In [15]:
X.loc[[0, 1895, 2590, 1240]]

,Gr Liv Area,Bedroom AbvGr,Bathrooms,Lot Area,House Style_1.5Fin,House Style_1.5Unf,House Style_1Story,House Style_2.5Fin,House Style_2.5Unf,House Style_2Story,...,Neighborhood_OldTown,Neighborhood_SWISU,Neighborhood_Sawyer,Neighborhood_SawyerW,Neighborhood_Somerst,Neighborhood_StoneBr,Neighborhood_Timber,Neighborhood_Veenker,Central Air_N,Central Air_Y
0,1656,3,1.0,31770,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1895,1652,3,1.5,22002,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2590,2039,3,1.5,21299,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1240,1570,3,1.0,13200,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1

**Once again, both the Euclidean and Manhattan methods returned the same house (house 1895) as the closest cheaper house to house 0. This time I also included the variables `Lot Area`, `Neighborhood`, and `Central Air`. Doing this seems to have affected the methods more than previously, as prior to this just about all the houses chosen have been the same between the two methods. However, this time the second, fourth, and fifth closest houses are different between the methods. This likely means that the more variables you consider, the more different the distance methods will be from each other.**

## Colleges similar to Cal Poly

We'll use data from the [College Scorecard data](https://collegescorecard.ed.gov/) to find colleges and universities that are similar to Cal Poly.

In [16]:
df_college = pd.read_csv("https://datasci112.stanford.edu/data/college_attributes.csv")

df_college.set_index("Institution", inplace = True)

df_college

,City,State,AdmissionRate,Undergraduates,CarnegieClassification,Ownership,PCIP01,PCIP03,PCIP04,PCIP05,...,PCIP44,PCIP45,PCIP46,PCIP47,PCIP48,PCIP49,PCIP50,PCIP51,PCIP52,PCIP54
Institution,,,,,,,,,,,,,,,,,,,,,
Alabama A & M University,Normal,AL,0.7160,5098.0,Master's Colleges & Universities: Larger Programs,Public,0.0445,0.0071,0.0053,0.0000,...,0.0409,0.0249,0.0,0.0,0.0,0.0,0.0231,0.0000,0.1637,0.0000
University of Alabama at Birmingham,Birmingham,AL,0.8854,13284.0,Doctoral Universities: Very High Research Acti...,Public,0.0000,0.0000,0.0000,0.0020,...,0.0195,0.0239,0.0,0.0,0.0,0.0,0.0249,0.2088,0.2159,0.0141
University of Alabama in Huntsville,Huntsville,AL,0.7367,7358.0,Doctoral Universities: Very High Research Acti...,Public,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0127,0.0,0.0,0.0,0.0,0.0407,0.1341,0.1930,0.0073
Alabama State University,Montgomery,AL,0.9799,3495.0,Doctoral/Professional Universities,Public,0.0000,0.0000,0.0000,0.0000,...,0.0648,0.0196,0.0,0.0,0.0,0.0,0.0511,0.0904,0.1513,0.0059
The University of Alabama,Tuscaloosa,AL,0.7890,30725.0,Doctoral Universities: Very High Research Acti...,Public,0.0000,0.0061,0.0000,0.0019,...,0.0072,0.0661,0.0,0.0,0.0,0.0,0.0234,0.1077,0.2916,0.0096
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Florida Academy of Nursing,Miramar,FL,0.3088,239.0,Not applicable,Private for-profit,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0000,1.0000,0.0000,0.0000
Herzing University-Tampa,Tampa,FL,0.9630,68.0,Not applicable,Private nonprofit,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000
Abilene Christian University-Undergraduate Online,Addison,TX,1.0000,415.0,Not applicable,Private nonprofit,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000
Great Northern University,Spokane,WA,1.0000,25.0,Not applicable,Private nonprofit,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0000,0.0000,0.1250,0.0000
Arizona College of Nursing-Salt Lake City,Murray,UT,1.0000,186.0,Not applicable,Private for-profit,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000

We'll want to single out Cal Poly, which we can do like this.

In [17]:
school_name = "California Polytechnic State University-San Luis Obispo"

cp = df_college.loc[school_name]

cp

City                                                        San Luis Obispo
State                                                                    CA
AdmissionRate                                                          0.33
Undergraduates                                                      21090.0
CarnegieClassification    Master's Colleges & Universities: Larger Programs
Ownership                                                            Public
PCIP01                                                               0.1084
PCIP03                                                               0.0255
PCIP04                                                               0.0441
PCIP05                                                               0.0019
PCIP09                                                               0.0353
PCIP10                                                               0.0175
PCIP11                                                               0.0326
PCIP12                                                                  0.0
PCIP13                                                                0.013
PCIP14                                                               0.2314
PCIP15                                                                0.011
PCIP16                                                               0.0019
PCIP19                                                                  0.0
PCIP22                                                                  0.0
PCIP23                                                               0.0147
PCIP24                                                               0.0229
PCIP25                                                                  0.0
PCIP26                                                               0.0495
PCIP27                                                               0.0173
PCIP29                                                                  0.0
PCIP30                                                               0.0223
PCIP31                                                               0.0419
PCIP38                                                               0.0073
PCIP39                                                                  0.0
PCIP40                                                               0.0205
PCIP41                                                                  0.0
PCIP42                                                               0.0288
PCIP43                                                                  0.0
PCIP44                                                                  0.0
PCIP45                                                               0.0588
PCIP46                                                                  0.0
PCIP47                                                                  0.0
PCIP48                                                                  0.0
PCIP49                                                                  0.0
PCIP50                                                                0.013
PCIP51                                                                0.006
PCIP52                                                               0.1637
PCIP54                                                                0.011
Name: California Polytechnic State University-San Luis Obispo, dtype: object

1\. Based on only the admission rate and the number of undergraduates, what schools are most similar to Cal Poly? Specify how you're making this decision.

In [18]:
show_vars = ["AdmissionRate", "Undergraduates"]
X = df_college[show_vars]
X

,AdmissionRate,Undergraduates
Institution,,
Alabama A & M University,0.7160,5098.0
University of Alabama at Birmingham,0.8854,13284.0
University of Alabama in Huntsville,0.7367,7358.0
Alabama State University,0.9799,3495.0
The University of Alabama,0.7890,30725.0
...,...,...
Florida Academy of Nursing,0.3088,239.0
Herzing University-Tampa,0.9630,68.0
Abilene Christian University-Undergraduate Online,1.0000,415.0
Great Northern University,1.0000,25.0
Arizona College of Nursing-Salt Lake City,1.0000,186.0

In [19]:
X_z = (X - X.mean()) / X.std()
diff = X_z - X_z.loc[school_name]
df_college["euclid"] = np.sqrt((diff**2).sum(axis=1))
df_college["manhattan"] = diff.abs().sum(axis=1)

In [20]:
df_college.sort_values("euclid")[show_vars + ["euclid"]].head().reset_index()

,Institution,AdmissionRate,Undergraduates,euclid
0,California Polytechnic State University-San Lu...,0.3300,21090.0,0.000000
1,University of California-Santa Barbara,0.2918,23081.0,0.309162
2,DeVry University-Illinois,0.4552,19729.0,0.593121
3,University of North Carolina at Chapel Hill,0.2040,19722.0,0.596846
4,Clemson University,0.4922,21577.0,0.736788

In [21]:
df_college.sort_values("manhattan")[show_vars + ["manhattan"]].head().reset_index()

,Institution,AdmissionRate,Undergraduates,manhattan
0,California Polytechnic State University-San Lu...,0.3300,21090.0,0.000000
1,University of California-Santa Barbara,0.2918,23081.0,0.429191
2,DeVry University-Illinois,0.4552,19729.0,0.741854
3,University of North Carolina at Chapel Hill,0.2040,19722.0,0.746376
4,Clemson University,0.4922,21577.0,0.796807

**Based solely on `AdmissionRate` and `Undergraduates`, looking at both the Euclidean and Manhattan distances, the closest scool to Cal Poly is UCSB, followed by DeVry University, UNC Chapel Hill, and Clemson University. However, UCSB is the closest by a wide margin.**

2\. Now consider the admission rate, the number of undergraduates, and also the [Carnegie classification](https://en.wikipedia.org/wiki/Carnegie_Classification_of_Institutions_of_Higher_Education) of the type of school, and the ownership (public, private, etc.) Based on these variables, what schools are most similar to Cal Poly? Specify how you're making this decision.

In [22]:
show_vars = ["AdmissionRate", "Undergraduates", "CarnegieClassification"]
X = df_college[show_vars]
X = pd.get_dummies(X) * 1
X

,AdmissionRate,Undergraduates,CarnegieClassification_Associate's Colleges: High Career & Technical-High Nontraditional,CarnegieClassification_Associate's Colleges: High Career & Technical-High Traditional,CarnegieClassification_Associate's Colleges: High Career & Technical-Mixed Traditional/Nontraditional,CarnegieClassification_Associate's Colleges: High Transfer-High Nontraditional,CarnegieClassification_Associate's Colleges: High Transfer-High Traditional,CarnegieClassification_Associate's Colleges: High Transfer-Mixed Traditional/Nontraditional,CarnegieClassification_Baccalaureate Colleges: Arts & Sciences Focus,CarnegieClassification_Baccalaureate Colleges: Diverse Fields,...,CarnegieClassification_Special Focus Four-Year: Faith-Related Institutions,CarnegieClassification_Special Focus Four-Year: Medical Schools & Centers,CarnegieClassification_Special Focus Four-Year: Other Health Professions Schools,CarnegieClassification_Special Focus Four-Year: Other Special Focus Institutions,CarnegieClassification_Special Focus Four-Year: Research Institution,CarnegieClassification_Special Focus Two-Year: Arts & Design,CarnegieClassification_Special Focus Two-Year: Health Professions,CarnegieClassification_Special Focus Two-Year: Other Fields,CarnegieClassification_Special Focus Two-Year: Technical Professions,CarnegieClassification_Tribal Colleges
Institution,,,,,,,,,,,,,,,,,,,,,
Alabama A & M University,0.7160,5098.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
University of Alabama at Birmingham,0.8854,13284.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
University of Alabama in Huntsville,0.7367,7358.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Alabama State University,0.9799,3495.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
The University of Alabama,0.7890,30725.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Florida Academy of Nursing,0.3088,239.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Herzing University-Tampa,0.9630,68.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Abilene Christian University-Undergraduate Online,1.0000,415.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Great Northern University,1.0000,25.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Arizona College of Nursing-Salt Lake City,1.0000,186.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
X_z = (X - X.mean()) / X.std()
diff = X_z - X_z.loc[school_name]
df_college["euclid"] = np.sqrt((diff**2).sum(axis=1))
df_college["manhattan"] = diff.abs().sum(axis=1)
df_college.sort_values("euclid")[show_vars + ["euclid"]].head().reset_index()

,Institution,AdmissionRate,Undergraduates,CarnegieClassification,euclid
0,California Polytechnic State University-San Lu...,0.3300,21090.0,Master's Colleges & Universities: Larger Programs,0.000000
1,DeVry University-Illinois,0.4552,19729.0,Master's Colleges & Universities: Larger Programs,0.593121
2,CUNY Hunter College,0.4590,17293.0,Master's Colleges & Universities: Larger Programs,0.761441
3,CUNY Bernard M Baruch College,0.5056,15483.0,Master's Colleges & Universities: Larger Programs,1.073601
4,CUNY John Jay College of Criminal Justice,0.4458,12834.0,Master's Colleges & Universities: Larger Programs,1.184989

In [24]:
df_college.sort_values("manhattan")[show_vars + ["manhattan"]].head().reset_index()

,Institution,AdmissionRate,Undergraduates,CarnegieClassification,manhattan
0,California Polytechnic State University-San Lu...,0.3300,21090.0,Master's Colleges & Universities: Larger Programs,0.000000
1,DeVry University-Illinois,0.4552,19729.0,Master's Colleges & Universities: Larger Programs,0.741854
2,CUNY Hunter College,0.4590,17293.0,Master's Colleges & Universities: Larger Programs,1.072635
3,CUNY Bernard M Baruch College,0.5056,15483.0,Master's Colleges & Universities: Larger Programs,1.516545
4,CUNY John Jay College of Criminal Justice,0.4458,12834.0,Master's Colleges & Universities: Larger Programs,1.586893

**When including `CarnegieClassification`, the list changes somewhat. DeVry University jumps to the closest to Cal Poly, followed by multiple CUNY schools, based on both the Euclidean and Manhattan distances.**

3\. The columns whose names begin with "PCIP" contain the proportions of students at each school studying various fields (e.g., Engineering, Psychology). Each field is represented by a two-digit code called the [CIP code](https://nces.ed.gov/ipeds/cipcode/browse.aspx?y=55).

If we only consider the proportions of students studying various fields, what schools are most similar to Cal Poly? Specify how you're making this decision.

In [25]:
show_vars = [col for col in df_college.columns if col.startswith("PCIP")]

X = df_college[show_vars]

X

,PCIP01,PCIP03,PCIP04,PCIP05,PCIP09,PCIP10,PCIP11,PCIP12,PCIP13,PCIP14,...,PCIP44,PCIP45,PCIP46,PCIP47,PCIP48,PCIP49,PCIP50,PCIP51,PCIP52,PCIP54
Institution,,,,,,,,,,,,,,,,,,,,,
Alabama A & M University,0.0445,0.0071,0.0053,0.0000,0.0000,0.0285,0.0658,0.0,0.0391,0.1210,...,0.0409,0.0249,0.0,0.0,0.0,0.0,0.0231,0.0000,0.1637,0.0000
University of Alabama at Birmingham,0.0000,0.0000,0.0000,0.0020,0.0333,0.0000,0.0229,0.0,0.0667,0.0559,...,0.0195,0.0239,0.0,0.0,0.0,0.0,0.0249,0.2088,0.2159,0.0141
University of Alabama in Huntsville,0.0000,0.0000,0.0000,0.0000,0.0140,0.0000,0.0692,0.0,0.0218,0.3028,...,0.0000,0.0127,0.0,0.0,0.0,0.0,0.0407,0.1341,0.1930,0.0073
Alabama State University,0.0000,0.0000,0.0000,0.0000,0.0923,0.0000,0.0530,0.0,0.0589,0.0138,...,0.0648,0.0196,0.0,0.0,0.0,0.0,0.0511,0.0904,0.1513,0.0059
The University of Alabama,0.0000,0.0061,0.0000,0.0019,0.0877,0.0000,0.0148,0.0,0.0262,0.1198,...,0.0072,0.0661,0.0,0.0,0.0,0.0,0.0234,0.1077,0.2916,0.0096
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Florida Academy of Nursing,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0000,1.0000,0.0000,0.0000
Herzing University-Tampa,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000
Abilene Christian University-Undergraduate Online,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000
Great Northern University,0.0000,0.0000,0.0000,0.0000,0.2500,0.0000,0.0000,0.0,0.2500,0.0000,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0000,0.0000,0.1250,0.0000
Arizona College of Nursing-Salt Lake City,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000

In [26]:
X_z = (X - X.mean()) / X.std()
diff = X_z - X_z.loc[school_name]
df_college["euclid"] = np.sqrt((diff**2).sum(axis=1))
df_college["manhattan"] = diff.abs().sum(axis=1)
df_college.sort_values("euclid")[show_vars + ["euclid"]].head().reset_index()

,Institution,PCIP01,PCIP03,PCIP04,PCIP05,PCIP09,PCIP10,PCIP11,PCIP12,PCIP13,...,PCIP45,PCIP46,PCIP47,PCIP48,PCIP49,PCIP50,PCIP51,PCIP52,PCIP54,euclid
0,California Polytechnic State University-San Lu...,0.1084,0.0255,0.0441,0.0019,0.0353,0.0175,0.0326,0.0000,0.0130,...,0.0588,0.0,0.0,0.0,0.0000,0.0130,0.0060,0.1637,0.0110,0.000000
1,Iowa State University,0.1013,0.0131,0.0163,0.0009,0.0392,0.0000,0.0428,0.0000,0.0473,...,0.0203,0.0,0.0,0.0,0.0000,0.0399,0.0131,0.1651,0.0069,1.986207
2,California State Polytechnic University-Pomona,0.0384,0.0000,0.0324,0.0043,0.0306,0.0000,0.0415,0.0000,0.0209,...,0.0785,0.0,0.0,0.0,0.0000,0.0295,0.0000,0.2937,0.0094,2.241726
3,Texas A & M University-College Station,0.0847,0.0241,0.0111,0.0001,0.0397,0.0000,0.0334,0.0000,0.0272,...,0.0593,0.0,0.0,0.0,0.0048,0.0010,0.0582,0.1593,0.0094,2.258942
4,Mississippi State University,0.0619,0.0263,0.0208,0.0000,0.0360,0.0000,0.0201,0.0002,0.0712,...,0.0367,0.0,0.0,0.0,0.0000,0.0102,0.0040,0.1825,0.0069,2.335288

In [27]:
df_college.sort_values("manhattan")[show_vars + ["manhattan"]].head().reset_index()

,Institution,PCIP01,PCIP03,PCIP04,PCIP05,PCIP09,PCIP10,PCIP11,PCIP12,PCIP13,...,PCIP45,PCIP46,PCIP47,PCIP48,PCIP49,PCIP50,PCIP51,PCIP52,PCIP54,manhattan
0,California Polytechnic State University-San Lu...,0.1084,0.0255,0.0441,0.0019,0.0353,0.0175,0.0326,0.0,0.0130,...,0.0588,0.0,0.0,0.0,0.0000,0.0130,0.0060,0.1637,0.0110,0.000000
1,Iowa State University,0.1013,0.0131,0.0163,0.0009,0.0392,0.0000,0.0428,0.0,0.0473,...,0.0203,0.0,0.0,0.0,0.0000,0.0399,0.0131,0.1651,0.0069,7.559127
2,California State Polytechnic University-Pomona,0.0384,0.0000,0.0324,0.0043,0.0306,0.0000,0.0415,0.0,0.0209,...,0.0785,0.0,0.0,0.0,0.0000,0.0295,0.0000,0.2937,0.0094,7.710675
3,Texas A & M University-College Station,0.0847,0.0241,0.0111,0.0001,0.0397,0.0000,0.0334,0.0,0.0272,...,0.0593,0.0,0.0,0.0,0.0048,0.0010,0.0582,0.1593,0.0094,8.063105
4,North Carolina State University at Raleigh,0.0906,0.0356,0.0075,0.0000,0.0353,0.0000,0.0366,0.0,0.0233,...,0.0467,0.0,0.0,0.0,0.0000,0.0155,0.0000,0.1580,0.0116,8.501392

**Including so many variables made the distances between Cal Poly and other schools much larger. But based solely on all the `PCIP` columns, the schools most similar to Cal Poly are Iowa State University, followed by Cal Poly Pomona and Texas A & M University, which makes sense due to the large population likely studying agricultural subjects.**